apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort : 32000
  type: NodePort
